### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by androidty** [pscj/crosswalk-lite-demo#1]
博主有没有X86的libxwalkcore.so文件？

**Comment by pscj** [comment]
可以去官方 [下载](https://download.01.org/crosswalk/releases/crosswalk-lite/android/canary/) 对应版本的

**Comment by androidty** [comment]
大神有用crosswalk集成h5游戏吗？，我集成联网的h5游戏运行时会有些卡顿，

**Comment by pscj** [comment]
还没试过游戏的支持，我们是做应用的
